version: 2

defaults: &defaults
  docker:
    - image: gentoo/stage3-amd64
  working_directory: /ci

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Prepare build
          command: |
            pwd
            ls ${CIRCLE_WORKING_DIRECTORY}
            rsync -vrtza ${CIRCLE_WORKING_DIRECTORY}/files/ /
            emerge-webrsync
            emerge -q eix
      - run:
          name: Build kernel
          command: |
            export KERNEL="4.12.5"
            emerge -q =sys-kernel/gentoo-sources-${KERNEL}
            mkdir /kernel
            cd /usr/src/linux-${KERNEL}-gentoo && \
                mkdir -p arch/x86_64/boot/ && \
                wget https://raw.githubusercontent.com/pgrandin/kernel-configs/master/precision-5510 -O .config && \
                wget https://github.com/pgrandin/kernel-configs/releases/download/4.12.5/precision-5510-${KERNEL} -O arch/x86_64/boot/bzImage || \
                $(( make -j24 && make modules_install INSTALL_MOD_PATH=/kernel/ ))
            cp arch/x86_64/boot/bzImage /kernel/vmlinuz-${KERNEL}
      - store_artifacts:
          path: /kernel
      - run:
          name: Build essential packages
          command: |
            emerge -q app-editors/vim app-misc/tmux app-admin/pass
            emerge -q net-wireless/wpa_supplicant net-wireless/wireless-tools
            emerge -q net-wireless/bluez net-wireless/rfkill
            emerge -q media-sound/alsa-utils
      - store_artifacts:
          path: /usr/portage/packages/
      - run:
          name: Build basic X packages
          command: |
            emerge -q x11-misc/slim
            emerge -q x11-base/xorg-server
            emerge -q x11-wm/i3 x11-misc/i3lock x11-misc/i3status
            emerge -q terminator
      - store_artifacts:
          path: /usr/portage/packages/
      - run:
          name: Build devops stuff
          command: emerge -q app-emulation/docker dev-python/boto3 dev-python/awscli
      - store_artifacts:
          path: /usr/portage/packages/
      - run:
          name: Build firefox
          command: emerge -q www-client/firefox
      - store_artifacts:
          path: /usr/portage/packages/
      - run:
          name: Build thunderbird
          command: emerge -q mail-client/thunderbird
      - store_artifacts:
          path: /usr/portage/packages/
