version: 2

defaults: &defaults
  docker:
    - image: gentoo/stage3-amd64

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false

      - run:
          name: Start build process
          command: |
            emerge-webrsync
            emerge -q eix
            emerge -q =sys-kernel/gentoo-sources-4.12.5
            cd /usr/src/linux-4.12.5-gentoo && \
                wget https://raw.githubusercontent.com/pgrandin/kernel-configs/master/precision-5510 -O .config && \
                make -j24 && make modules_install && make install




