version: 2

defaults: &defaults
  docker:
    - image: gentoo/stage3-amd64

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false

      - run:
          name: Prepare build
          command: |
            rsync -vrtza ${CIRCLE_WORKING_DIRECTORY}/${CIRCLE_PROJECT_REPONAME}/files/ /
            emerge-webrsync
            emerge -q eix
      - run:
          name: Build kernel
          command: |
            export KERNEL="4.12.5"
            emerge -q =sys-kernel/gentoo-sources-${KERNEL}
            mkdir /kernel
            cd /usr/src/linux-${KERNEL}-gentoo && \
                wget https://raw.githubusercontent.com/pgrandin/kernel-configs/master/precision-5510 -O .config && \
                make -j24 && make modules_install INSTALL_MOD_PATH=/kernel/ && \
                cp arch/x86_64/boot/bzImage /kernel/vmlinuz-${KERNEL}
      - store_artifacts:
          path: /kernel
      - run:
          name: Build packages
          command: |
            emerge -q app-editors/vim app-misc/tmux
            emerge -q net-wireless/wpa_supplicant net-wireless/wireless-tools
            emerge -q net-wireless/bluez net-wireless/rfkill
            emerge -q media-sound/alsa-utils
            emerge -q x11-misc/slim
            emerge -q x11-base/xorg-server
            emerge -q x11-wm/i3 x11-misc/i3lock x11-misc/i3status
      - store_artifacts:
          path: /usr/portage/packages/
